redis:
  host: localhost
  port: 6379
  dbIndex: 0
  password: 
server:
    port: 8090
joinfaces:
  richfaces:
    base-skin: ruby
    skin: ruby
spring:
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/backoffice
    username: postgres
    password: mypassword
    driver-class-name: org.postgresql.Driver
    platform: postgres
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
rest:
  client:
    sslbypass: true
    readTimeout: 10000