redis:
  host: localhost
  port: 6379
  dbIndex: 0
  password: r3d1sp4s$
joinfaces:
  richfaces:
    base-skin: ruby
    skin: ruby
spring:
  datasource:
    name: datasource
    url: jdbc:postgresql://localhost:5432/omni-administrator
    username: "omni-administrator"
    password: "p4ss0rd!5398@#$s"
    driver-class-name: org.postgresql.Driver
    platform: mysql
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    hikari:
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 40
      minimum-idle: 10
      pool-name: omniadministratordbpool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
  jpa:
    hibernate:
      connection:
        provider_class: "com.zaxxer.hikari.hibernate.HikariConnectionProvider"
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        hbm2ddl.auto: update
        jdbc.lob.non_contextual_creation: true
        order_updates: true
        batch_versioned_data: true
api:
  micro:
    path: '/api/administrator'
  key:
    internal: "817a2be3-2b92-4f55-a740-e290ce63242f"
swagger:
  host: "localhost:8090"
app:
  web:
    path: '/apps'
  redis:
    userexpiration: 720
  jwt:
    expiration: 720
    refreshexpiration: 10800
    secret: "Aval4nch3X8_a!324$"
    refreshsecret: "TuRb0$_p!934#"
  user:
    regexPasswd: "(?=.*\\d)(?=.*[a-z])(?=.*[A-Z]).{8,20}$"
    defaultpassword : "c0d3FuN0mn1"
rest:
  client:
    sslbypass: true
    readTimeout: 10000